### ISSUE TITLE
Can't change categories and crash issue

### ISSUE THREAD

**Issue by K4Z3R0** [jmir1/aniyomi-mpv-beta#99]
I can't change categories at the moment. And I can't open the app because it keeps crashing. I suspect that the issue is related to the category, because my device restart every time I try to open Aniyomi-mpv.

**Crashlog**

```
--------- beginning of crash
07-17 03:27:23.612  3334  3413 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
07-17 03:27:23.612  3334  3413 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi.debug, PID: 3334
07-17 03:27:23.612  3334  3413 E AndroidRuntime: java.lang.IllegalArgumentException: Comparison method violates its general contract!
07-17 03:27:23.612  3334  3413 E AndroidRuntime: 	at java.util.TimSort.mergeLo(TimSort.java:777)
07-17 03:27:23.612  3334  3413 E AndroidRuntime: 	at java.util.TimSort.mergeAt(TimSort.java:514)
07-17 03:27:23.612  3334  3413 E AndroidRuntime: 	at java.util.TimSort.mergeCollapse(TimSort.java:441)
07-17 03:27:23.612  3334  3413 E AndroidRuntime: 	at java.util.TimSort.sort(TimSort.java:245)
07-17 03:27:23.612  3334  3413 E AndroidRuntime: 	at java.util.Arrays.sort(Arrays.java:1424)
07-17 03:27:23.612  3334  3413 E AndroidRuntime: 	at kotlin.collections.ArraysKt___ArraysJvmKt.sortWith(_ArraysJvm.kt:1)
07-17 03:27:23.612  3334  3413 E AndroidRuntime: 	at kotlin.collections.CollectionsKt___CollectionsKt.sortedWith(_Collections.kt:37)
07-17 03:27:23.612  3334  3413 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.anime.AnimeLibraryScreenModel$1$2.invokeSuspend(AnimeLibraryScreenModel.kt:224)
07-17 03:27:23.612  3334  3413 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
07-17 03:27:23.612  3334  3413 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:97)
07-17 03:27:23.612  3334  3413 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
07-17 03:27:23.612  3334  3413 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
07-17 03:27:23.612  3334  3413 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
07-17 03:27:23.612  3334  3413 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
07-17 03:27:23.612  3334  3413 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(eu.kanade.tachiyomi.ui.library.anime.AnimeLibraryTab:eu.kanade.tachiyomi.ui.library.anime.AnimeLibraryScreenModel:default:ScreenModelCoroutineScope), StandaloneCoroutine{Cancelling}@14c71bf, Dispatchers.IO]
--------- beginning of main
07-17 03:33:08.722  9143  9143 E hiyomi.mi.debu: Unknown bits set in runtime_flags: 0x8000
07-17 03:33:08.726  9143  9143 E hiyomi.mi.debu: Not starting debugger since process cannot load the jdwp agent.
--------- beginning of system
07-17 03:33:09.238  9143  9143 E libc    : Access denied finding property "ro.vendor.scaler_version"
07-17 03:33:09.239  9143  9143 E libc    : Access denied finding property "ro.vendor.scaler_version"
07-17 03:33:10.101  9143  9183 E SQLiteLog: (284) automatic index on C(anime_id)
07-17 03:33:10.101  9143  9183 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
07-17 03:33:10.590  9272  9272 E g:error_handle: Unknown bits set in runtime_flags: 0x8000
07-17 03:33:10.593  9272  9272 E g:error_handle: Not starting debugger since process cannot load the jdwp agent.
07-17 03:33:10.763  9272  9300 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
07-17 03:33:10.764  9272  9299 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
07-17 03:33:10.849  9272  9272 E libc    : Access denied finding property "ro.vendor.scaler_version"
07-17 03:33:10.850  9272  9272 E libc    : Access denied finding property "ro.vendor.scaler_version"
07-17 03:33:11.680  9272  9301 E gralloc : Arm Module v1.0
07-17 03:33:11.681  9272  9301 E ion     : ioctl c0044901 failed with code -1: Invalid argument
App version: 0.14.5-6453 (standard, 78822adb3, 99, 2023-07-14T17:34Z)
Android version: 10 (SDK 29)
Android build ID: KE7-H693HJKM-Q-GL-220729V478
Device brand: TECNO
Device manufacturer: TECNO MOBILE LIMITED
Device name: TECNO-KE7
Device model: TECNO KE7
Device product name: KE7-GL
```

**Comment by fakebhai** [comment]
device restart???? scary
